
server:
  port: 8065
 
spring:
  datasource:
    username: oa_user
    password: 123456
    url: jdbc:mysql://localhost:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.wwx.his.cd.model,com.wwx.his.admin.model,com.wwx.his.drug.model,com.wwx.his.pst.model
 
#showSql
logging:
  level:
    com.wwx.his: debug
